module BestestCaseVarLib

  # define cases for section 5.2.3
  def self.bestest_5_2_3_case_defs()

    variable_hash_lookup = {}
    variable_hash_lookup['195'] = [
        :htg_set => 20.0,
        :clg_set => 20.0,
        :mass => 'L',
        :int_gen => 0.0,
        :infil => 0.0,
        :int_ir_emit => 0.1,
        :ext_ir_emit => 0.1,
        :int_sw_absorpt => nil,
        :ext_sw_absorpt => 0.1,
        :glass_area => nil,
        :orient => 'S',
        :shade => false,
        :shade_type => nil,
        :ff => false,
        :b1_1_note_01 => true,
        :b1_1_note_02 => true,
        :b1_1_note_03 => false
    ]
    variable_hash_lookup['200'] = [
        :htg_set => 20.0,
        :clg_set => 20.0,
        :mass => 'L',
        :int_gen => 0.0,
        :infil => 0.0,
        :int_ir_emit => 0.1,
        :ext_ir_emit => 0.1,
        :int_sw_absorpt => nil,
        :ext_sw_absorpt => 0.1,
        :glass_area => nil,
        :orient => 'S',
        :shade => false,
        :shade_type => nil,
        :ff => false,
        :b1_1_note_01 => true,
        :b1_1_note_02 => false,
        :b1_1_note_03 => true
    ]
    variable_hash_lookup['210'] = [
        :htg_set => 20.0,
        :clg_set => 20.0,
        :mass => 'L',
        :int_gen => 0.0,
        :infil => 0.0,
        :int_ir_emit => 0.1,
        :ext_ir_emit => 0.9,
        :int_sw_absorpt => nil,
        :ext_sw_absorpt => 0.1,
        :glass_area => 0.0,
        :orient => 'S',
        :shade => false,
        :shade_type => nil,
        :ff => false,
        :b1_1_note_01 => true,
        :b1_1_note_02 => false,
        :b1_1_note_03 => false
    ]
    variable_hash_lookup['215'] = [
        :htg_set => 20.0,
        :clg_set => 20.0,
        :mass => 'L',
        :int_gen => 0.0,
        :infil => 0.0,
        :int_ir_emit => 0.9,
        :ext_ir_emit => 0.1,
        :int_sw_absorpt => nil,
        :ext_sw_absorpt => 0.1,
        :glass_area => 0.0,
        :orient => 'S',
        :shade => false,
        :shade_type => nil,
        :ff => false,
        :b1_1_note_01 => true,
        :b1_1_note_02 => false,
        :b1_1_note_03 => false
    ]
    variable_hash_lookup['220'] = [
        :htg_set => 20.0,
        :clg_set => 20.0,
        :mass => 'L',
        :int_gen => 0.0,
        :infil => 0.0,
        :int_ir_emit => 0.9,
        :ext_ir_emit => 0.9,
        :int_sw_absorpt => nil,
        :ext_sw_absorpt => 0.1,
        :glass_area => 0.0,
        :orient => 'S',
        :shade => false,
        :shade_type => nil,
        :ff => false,
        :b1_1_note_01 => true,
        :b1_1_note_02 => false,
        :b1_1_note_03 => false
    ]
    variable_hash_lookup['230'] = [
        :htg_set => 20.0,
        :clg_set => 20.0,
        :mass => 'L',
        :int_gen => 0.0,
        :infil => 1.0,
        :int_ir_emit => 0.9,
        :ext_ir_emit => 0.9,
        :int_sw_absorpt => nil,
        :ext_sw_absorpt => 0.1,
        :glass_area => 0.0,
        :orient => 'S',
        :shade => false,
        :shade_type => nil,
        :ff => false,
        :b1_1_note_01 => true,
        :b1_1_note_02 => false,
        :b1_1_note_03 => false
    ]
    variable_hash_lookup['240'] = [
        :htg_set => 20.0,
        :clg_set => 20.0,
        :mass => 'L',
        :int_gen => 200.0,
        :infil => 0.0,
        :int_ir_emit => 0.9,
        :ext_ir_emit => 0.9,
        :int_sw_absorpt => nil,
        :ext_sw_absorpt => 0.1,
        :glass_area => 0.0,
        :orient => 'S',
        :shade => false,
        :shade_type => nil,
        :ff => false,
        :b1_1_note_01 => true,
        :b1_1_note_02 => false,
        :b1_1_note_03 => false
    ]
    variable_hash_lookup['250'] = [
        :htg_set => 20.0,
        :clg_set => 20.0,
        :mass => 'L',
        :int_gen => 0.0,
        :infil => 0.0,
        :int_ir_emit => 0.9,
        :ext_ir_emit => 0.9,
        :int_sw_absorpt => nil,
        :ext_sw_absorpt => 0.9,
        :glass_area => 0.0,
        :orient => 'S',
        :shade => false,
        :shade_type => nil,
        :ff => false,
        :b1_1_note_01 => true,
        :b1_1_note_02 => false,
        :b1_1_note_03 => false
    ]
    variable_hash_lookup['270'] = [
        :htg_set => 20.0,
        :clg_set => 20.0,
        :mass => 'L',
        :int_gen => 0.0,
        :infil => 0.0,
        :int_ir_emit => 0.9,
        :ext_ir_emit => 0.9,
        :int_sw_absorpt => 0.9,
        :ext_sw_absorpt => 0.1,
        :glass_area => 12.0,
        :orient => 'S',
        :shade => false,
        :shade_type => nil,
        :ff => false,
        :b1_1_note_01 => false,
        :b1_1_note_02 => false,
        :b1_1_note_03 => false
    ]
    variable_hash_lookup['280'] = [
        :htg_set => 20.0,
        :clg_set => 20.0,
        :mass => 'L',
        :int_gen => 0.0,
        :infil => 0.0,
        :int_ir_emit => 0.9,
        :ext_ir_emit => 0.9,
        :int_sw_absorpt => 0.1,
        :ext_sw_absorpt => 0.1,
        :glass_area => 12.0,
        :orient => 'S',
        :shade => false,
        :shade_type => nil,
        :ff => false,
        :b1_1_note_01 => false,
        :b1_1_note_02 => false,
        :b1_1_note_03 => false
    ]
    variable_hash_lookup['290'] = [
        :htg_set => 20.0,
        :clg_set => 20.0,
        :mass => 'L',
        :int_gen => 0.0,
        :infil => 0.0,
        :int_ir_emit => 0.9,
        :ext_ir_emit => 0.9,
        :int_sw_absorpt => 0.9,
        :ext_sw_absorpt => 0.1,
        :glass_area => 12.0,
        :orient => 'S',
        :shade => 1.0,
        :shade_type => 'H',
        :ff => false,
        :b1_1_note_01 => false,
        :b1_1_note_02 => false,
        :b1_1_note_03 => false
    ]
    variable_hash_lookup['300'] = [
        :htg_set => 20.0,
        :clg_set => 20.0,
        :mass => 'L',
        :int_gen => 0.0,
        :infil => 0.0,
        :int_ir_emit => 0.9,
        :ext_ir_emit => 0.9,
        :int_sw_absorpt => 0.9,
        :ext_sw_absorpt => 0.1,
        :glass_area => 6.0,
        :orient => 'E,W',
        :shade => false,
        :shade_type => nil,
        :ff => false,
        :b1_1_note_01 => false,
        :b1_1_note_02 => false,
        :b1_1_note_03 => false
    ]
    variable_hash_lookup['310'] = [
        :htg_set => 20.0,
        :clg_set => 20.0,
        :mass => 'L',
        :int_gen => 0.0,
        :infil => 0.0,
        :int_ir_emit => 0.9,
        :ext_ir_emit => 0.9,
        :int_sw_absorpt => 0.9,
        :ext_sw_absorpt => 0.1,
        :glass_area => 6.0,
        :orient => 'E,W',
        :shade => 1.0,
        :shade_type => 'H,V',
        :ff => false,
        :b1_1_note_01 => false,
        :b1_1_note_02 => false,
        :b1_1_note_03 => false
    ]
    variable_hash_lookup['320'] = [
        :htg_set => 20.0,
        :clg_set => 27.0,
        :mass => 'L',
        :int_gen => 0.0,
        :infil => 0.0,
        :int_ir_emit => 0.9,
        :ext_ir_emit => 0.9,
        :int_sw_absorpt => 0.9,
        :ext_sw_absorpt => 0.1,
        :glass_area => 12.0,
        :orient => 'S',
        :shade => false,
        :shade_type => nil,
        :ff => false,
        :b1_1_note_01 => false,
        :b1_1_note_02 => false,
        :b1_1_note_03 => false
    ]
    variable_hash_lookup['395'] = [
        :htg_set => 20.0,
        :clg_set => 27.0,
        :mass => 'L',
        :int_gen => 0.0,
        :infil => 0.0,
        :int_ir_emit => 0.9,
        :ext_ir_emit => 0.9,
        :int_sw_absorpt => nil,
        :ext_sw_absorpt => 0.1,
        :glass_area => nil,
        :orient => 'S',
        :shade => false,
        :shade_type => nil,
        :ff => false,
        :b1_1_note_01 => true,
        :b1_1_note_02 => true,
        :b1_1_note_03 => false
    ]
    variable_hash_lookup['400'] = [
        :htg_set => 20.0,
        :clg_set => 27.0,
        :mass => 'L',
        :int_gen => 0.0,
        :infil => 0.0,
        :int_ir_emit => 0.9,
        :ext_ir_emit => 0.9,
        :int_sw_absorpt => nil,
        :ext_sw_absorpt => 0.1,
        :glass_area => 0.0,
        :orient => 'S',
        :shade => false,
        :shade_type => nil,
        :ff => false,
        :b1_1_note_01 => true,
        :b1_1_note_02 => false,
        :b1_1_note_03 => false
    ]
    variable_hash_lookup['410'] = [
        :htg_set => 20.0,
        :clg_set => 27.0,
        :mass => 'L',
        :int_gen => 0.0,
        :infil => 0.5,
        :int_ir_emit => 0.9,
        :ext_ir_emit => 0.9,
        :int_sw_absorpt => nil,
        :ext_sw_absorpt => 0.1,
        :glass_area => 0.0,
        :orient => 'S',
        :shade => false,
        :shade_type => nil,
        :ff => false,
        :b1_1_note_01 => true,
        :b1_1_note_02 => false,
        :b1_1_note_03 => false
    ]
    variable_hash_lookup['420'] = [
        :htg_set => 20.0,
        :clg_set => 27.0,
        :mass => 'L',
        :int_gen => 200.0,
        :infil => 0.5,
        :int_ir_emit => 0.9,
        :ext_ir_emit => 0.9,
        :int_sw_absorpt => nil,
        :ext_sw_absorpt => 0.1,
        :glass_area => 0.0,
        :orient => 'S',
        :shade => false,
        :shade_type => nil,
        :ff => false,
        :b1_1_note_01 => true,
        :b1_1_note_02 => false,
        :b1_1_note_03 => false
    ]
    variable_hash_lookup['430'] = [
        :htg_set => 20.0,
        :clg_set => 27.0,
        :mass => 'L',
        :int_gen => 200.0,
        :infil => 0.5,
        :int_ir_emit => 0.9,
        :ext_ir_emit => 0.9,
        :int_sw_absorpt => nil,
        :ext_sw_absorpt => 0.6,
        :glass_area => 0.0,
        :orient => 'S',
        :shade => false,
        :shade_type => nil,
        :ff => false,
        :b1_1_note_01 => true,
        :b1_1_note_02 => false,
        :b1_1_note_03 => false
    ]
    variable_hash_lookup['440'] = [
        :htg_set => 20.0,
        :clg_set => 27.0,
        :mass => 'L',
        :int_gen => 200.0,
        :infil => 0.5,
        :int_ir_emit => 0.9,
        :ext_ir_emit => 0.9,
        :int_sw_absorpt => 0.1,
        :ext_sw_absorpt => 0.6,
        :glass_area => 12.0,
        :orient => 'S',
        :shade => false,
        :shade_type => nil,
        :ff => false,
        :b1_1_note_01 => false,
        :b1_1_note_02 => false,
        :b1_1_note_03 => false
    ]
    variable_hash_lookup['600 - Base Case'] = [
        :htg_set => 20.0,
        :clg_set => 27.0,
        :mass => 'L',
        :int_gen => 200.0,
        :infil => 0.5,
        :int_ir_emit => 0.9,
        :ext_ir_emit => 0.9,
        :int_sw_absorpt => 0.6,
        :ext_sw_absorpt => 0.6,
        :glass_area => 12.0,
        :orient => 'S',
        :shade => false,
        :shade_type => nil,
        :ff => false,
        :b1_1_note_01 => false,
        :b1_1_note_02 => false,
        :b1_1_note_03 => false
    ]
    variable_hash_lookup['610 - South Shading'] = [
        :htg_set => 20.0,
        :clg_set => 27.0,
        :mass => 'L',
        :int_gen => 200.0,
        :infil => 0.5,
        :int_ir_emit => 0.9,
        :ext_ir_emit => 0.9,
        :int_sw_absorpt => 0.6,
        :ext_sw_absorpt => 0.6,
        :glass_area => 12.0,
        :orient => 'S',
        :shade => 1.0,
        :shade_type => 'H',
        :ff => false,
        :b1_1_note_01 => false,
        :b1_1_note_02 => false,
        :b1_1_note_03 => false
    ]
    variable_hash_lookup['620 - East West Window Orientation'] = [
        :htg_set => 20.0,
        :clg_set => 27.0,
        :mass => 'L',
        :int_gen => 200.0,
        :infil => 0.5,
        :int_ir_emit => 0.9,
        :ext_ir_emit => 0.9,
        :int_sw_absorpt => 0.6,
        :ext_sw_absorpt => 0.6,
        :glass_area => 6.0,
        :orient => 'E,W',
        :shade => false,
        :shade_type => nil,
        :ff => false,
        :b1_1_note_01 => false,
        :b1_1_note_02 => false,
        :b1_1_note_03 => false
    ]
    variable_hash_lookup['630 - East West Shading'] = [
        :htg_set => 20.0,
        :clg_set => 27.0,
        :mass => 'L',
        :int_gen => 200.0,
        :infil => 0.5,
        :int_ir_emit => 0.9,
        :ext_ir_emit => 0.9,
        :int_sw_absorpt => 0.6,
        :ext_sw_absorpt => 0.6,
        :glass_area => 6.0,
        :orient => 'E,W',
        :shade => '1.0',
        :shade_type => 'H,V',
        :ff => false,
        :b1_1_note_01 => false,
        :b1_1_note_02 => false,
        :b1_1_note_03 => false
    ]
    variable_hash_lookup['640 - Thermostat Setback'] = [
        :htg_set => 'SETBACK',
        :clg_set => 'SETBACK',
        :mass => 'L',
        :int_gen => 200.0,
        :infil => 0.5,
        :int_ir_emit => 0.9,
        :ext_ir_emit => 0.9,
        :int_sw_absorpt => 0.6,
        :ext_sw_absorpt => 0.6,
        :glass_area => 12.0,
        :orient => 'S',
        :shade => false,
        :shade_type => nil,
        :ff => false,
        :b1_1_note_01 => false,
        :b1_1_note_02 => false,
        :b1_1_note_03 => false
    ]
    variable_hash_lookup['650 - Night Ventilation'] = [
        :htg_set => 27.0,
        :clg_set => 'V',
        :mass => 'L',
        :int_gen => 200.0,
        :infil => 0.5,
        :int_ir_emit => 0.9,
        :ext_ir_emit => 0.9,
        :int_sw_absorpt => 0.6,
        :ext_sw_absorpt => 0.6,
        :glass_area => 12.0,
        :orient => 'S',
        :shade => false,
        :shade_type => nil,
        :ff => false,
        :b1_1_note_01 => false,
        :b1_1_note_02 => false,
        :b1_1_note_03 => false
    ]
    variable_hash_lookup['800'] = [
        :htg_set => 20.0,
        :clg_set => 27.0,
        :mass => 'H',
        :int_gen => 200.0,
        :infil => 0.5,
        :int_ir_emit => 0.9,
        :ext_ir_emit => 0.9,
        :int_sw_absorpt => nil,
        :ext_sw_absorpt => 0.6,
        :glass_area => 0.0,
        :orient => 'S',
        :shade => false,
        :shade_type => nil,
        :ff => false,
        :b1_1_note_01 => true,
        :b1_1_note_02 => false,
        :b1_1_note_03 => false
    ]
    variable_hash_lookup['810'] = [
        :htg_set => 20.0,
        :clg_set => 27.0,
        :mass => 'H',
        :int_gen => 200.0,
        :infil => 0.5,
        :int_ir_emit => 0.9,
        :ext_ir_emit => 0.9,
        :int_sw_absorpt => 0.1,
        :ext_sw_absorpt => 0.6,
        :glass_area => 12.0,
        :orient => 'S',
        :shade => false,
        :shade_type => nil,
        :ff => false,
        :b1_1_note_01 => false,
        :b1_1_note_02 => false,
        :b1_1_note_03 => false
    ]
    variable_hash_lookup['900 - High Mass Base Case'] = [
        :htg_set => 20.0,
        :clg_set => 27.0,
        :mass => 'H',
        :int_gen => 200.0,
        :infil => 0.5,
        :int_ir_emit => 0.9,
        :ext_ir_emit => 0.9,
        :int_sw_absorpt => 0.6,
        :ext_sw_absorpt => 0.6,
        :glass_area => 12.0,
        :orient => 'S',
        :shade => false,
        :shade_type => nil,
        :ff => false,
        :b1_1_note_01 => false,
        :b1_1_note_02 => false,
        :b1_1_note_03 => false
    ]
    variable_hash_lookup['910 - High Mass South Shading'] = [
        :htg_set => 20.0,
        :clg_set => 27.0,
        :mass => 'H',
        :int_gen => 200.0,
        :infil => 0.5,
        :int_ir_emit => 0.9,
        :ext_ir_emit => 0.9,
        :int_sw_absorpt => 0.6,
        :ext_sw_absorpt => 0.6,
        :glass_area => 12.0,
        :orient => 'S',
        :shade => 1.0,
        :shade_type => 'H',
        :ff => false,
        :b1_1_note_01 => false,
        :b1_1_note_02 => false,
        :b1_1_note_03 => false
    ]
    variable_hash_lookup['920 - High Mass East West Window Orientation'] = [
        :htg_set => 20.0,
        :clg_set => 27.0,
        :mass => 'H',
        :int_gen => 200.0,
        :infil => 0.5,
        :int_ir_emit => 0.9,
        :ext_ir_emit => 0.9,
        :int_sw_absorpt => 0.6,
        :ext_sw_absorpt => 0.6,
        :glass_area => 6.0,
        :orient => 'E,W',
        :shade => false,
        :shade_type => nil,
        :ff => false,
        :b1_1_note_01 => false,
        :b1_1_note_02 => false,
        :b1_1_note_03 => false
    ]
    variable_hash_lookup['930 - High Mass East West Shading'] = [
        :htg_set => 20.0,
        :clg_set => 27.0,
        :mass => 'H',
        :int_gen => 200.0,
        :infil => 0.5,
        :int_ir_emit => 0.9,
        :ext_ir_emit => 0.9,
        :int_sw_absorpt => 0.6,
        :ext_sw_absorpt => 0.6,
        :glass_area => 6.0,
        :orient => 'E,W',
        :shade => 1.0,
        :shade_type => 'H,V',
        :ff => false,
        :b1_1_note_01 => false,
        :b1_1_note_02 => false,
        :b1_1_note_03 => false
    ]
    variable_hash_lookup['940 - High Mass Thermostat Setback'] = [
        :htg_set => 'SETBACK',
        :clg_set => 'SETBACK',
        :mass => 'H',
        :int_gen => 200.0,
        :infil => 0.5,
        :int_ir_emit => 0.9,
        :ext_ir_emit => 0.9,
        :int_sw_absorpt => 0.6,
        :ext_sw_absorpt => 0.6,
        :glass_area => 12.0,
        :orient => 'S',
        :shade => false,
        :shade_type => nil,
        :ff => false,
        :b1_1_note_01 => false,
        :b1_1_note_02 => false,
        :b1_1_note_03 => false
    ]
    variable_hash_lookup['950 - High Mass Night Ventilation'] = [
        :htg_set => 27.0,
        :clg_set => 'V',
        :mass => 'H',
        :int_gen => 200.0,
        :infil => 0.5,
        :int_ir_emit => 0.9,
        :ext_ir_emit => 0.9,
        :int_sw_absorpt => 0.6,
        :ext_sw_absorpt => 0.6,
        :glass_area => 12.0,
      :orient => 'S',
        :shade => false,
        :shade_type => nil,
        :ff => false,
        :b1_1_note_01 => false,
        :b1_1_note_02 => false,
        :b1_1_note_03 => false
    ]
    # this case doesn't have any of the typical variables as other cases. Treat as custom solution
    variable_hash_lookup['960 - Sunspace'] = [
        :custom => true,
    ]
    variable_hash_lookup['600FF'] = [
        :htg_set => 20.0,
        :clg_set => 27.0,
        :mass => 'L',
        :int_gen => 200.0,
        :infil => 0.5,
        :int_ir_emit => 0.9,
        :ext_ir_emit => 0.9,
        :int_sw_absorpt => 0.6,
        :ext_sw_absorpt => 0.6,
        :glass_area => 12.0,
        :orient => 'S',
        :shade => false,
        :shade_type => nil,
        :ff => true,
        :b1_1_note_01 => false,
        :b1_1_note_02 => false,
        :b1_1_note_03 => false
    ]
    variable_hash_lookup['900FF'] = [
        :htg_set => 20.0,
        :clg_set => 27.0,
        :mass => 'H',
        :int_gen => 200.0,
        :infil => 0.5,
        :int_ir_emit => 0.9,
        :ext_ir_emit => 0.9,
        :int_sw_absorpt => 0.6,
        :ext_sw_absorpt => 0.6,
        :glass_area => 12.0,
        :orient => 'S',
        :shade => false,
        :shade_type => nil,
        :ff => true,
        :b1_1_note_01 => false,
        :b1_1_note_02 => false,
        :b1_1_note_03 => false
    ]
    variable_hash_lookup['650FF'] = [
        :htg_set => 27.0,
        :clg_set => 'V',
        :mass => 'L',
        :int_gen => 200.0,
        :infil => 0.5,
        :int_ir_emit => 0.9,
        :ext_ir_emit => 0.9,
        :int_sw_absorpt => 0.6,
        :ext_sw_absorpt => 0.6,
        :glass_area => 12.0,
        :orient => 'S',
        :shade => false,
        :shade_type => nil,
        :ff => true,
        :b1_1_note_01 => false,
        :b1_1_note_02 => false,
        :b1_1_note_03 => false
    ]
    variable_hash_lookup['950FF'] = [
        :htg_set => 27.0,
        :clg_set => 'V',
        :mass => 'H',
        :int_gen => 200.0,
        :infil => 0.5,
        :int_ir_emit => 0.9,
        :ext_ir_emit => 0.9,
        :int_sw_absorpt => 0.6,
        :ext_sw_absorpt => 0.6,
        :glass_area => 12.0,
        :orient => 'S',
        :shade => false,
        :shade_type => nil,
        :ff => true,
        :b1_1_note_01 => false,
        :b1_1_note_02 => false,
        :b1_1_note_03 => false
    ]

    return variable_hash_lookup

  end

  # lookup variables for section 5.2.3 based on case number
  def self.bestest_5_2_3_case_lookup(case_num,runner)

    # lookup case variables
    variable_hash_lookup = BestestCaseVarLib.bestest_5_2_3_case_defs

    # error if can't find expected case
    if variable_hash_lookup[case_num].nil?
      # didn't find expected case
      return false
    else
      variable_hash = variable_hash_lookup[case_num]
    end

    # report out variables in info statements
    variable_hash.first.each do |k,v|
      runner.registerInfo("For case #{case_num} the value for #{k} is #{v}")
    end

    return variable_hash

  end

end
